name: jetleaf_data
description: Core data module for JetLeaf â€” provides unified access to databases, caching, and storage backends.
version: 1.1.3

homepage: https://jetleaf.hapnium.com
repository: https://github.com/jetleaf/jetleaf_data
issue_tracker: https://github.com/jetleaf/jetleaf_data/issues
documentation: https://jetleaf.hapnium.com/docs/data

topics:
  - data
  - database
  - storage
  - jetleaf
  - orm

keywords:
  - jetleaf
  - data
  - database
  - storage
  - orm

environment:
  sdk: ^3.9.0

dependencies:
  meta: ^1.17.0
  jetleaf_lang: ^1.1.3
  jetleaf_logging: ^1.1.3
  jetleaf_pod: ^1.1.4
  jetleaf_core: ^1.1.5

dev_dependencies:
  test: ^1.28.0
  lints: ^6.0.0